In [1]:
from kendama_env import KendamaEnv
import numpy as np
import time
env = KendamaEnv()


start_time = time.time()
while 1:
    current_time = time.time()
    elapsed_time = current_time - start_time

    if elapsed_time > 1.0/env.dt:
        start_time = time.time()
        # action = [[2,8,10],[10,0,0]]
        action = [list(np.random.normal(scale = 0,size = 3)),list(np.random.normal(scale = 10,size = 3))]
        ob, reward, done, _ = env.step(action)
        break

[[(-0.00041584540446680545, -2.2433005897488298e-05, 0.07381058544907484)
  ((-0.010548614149981256, -0.005384963508892564, -0.017979447118291938), (55.36249452792139, -99.60950302836652, -99.99790570934304))
  (array([-0.00105486, -0.0005385 , -0.00179794]), array([ 5.53624945, -9.9609503 , -9.99979057]))]
 [(-7.549920042196525e-06, -0.00023572752232363866, 0.35181722650836206)
  ((0.0, 0.0, -0.04166666666666667), (0.0, 0.0, 0.0))
  (array([ 0.        ,  0.        , -0.00416667]), array([0., 0., 0.]))]]


In [3]:
ob[0]

array([(-0.00041584540446680545, -2.2433005897488298e-05, 0.07381058544907484),
       ((-0.010548614149981256, -0.005384963508892564, -0.017979447118291938), (55.36249452792139, -99.60950302836652, -99.99790570934304)),
       (array([-0.00105486, -0.0005385 , -0.00179794]), array([ 5.53624945, -9.9609503 , -9.99979057]))],
      dtype=object)